# Generated by Django 4.2.7 on 2023-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('lte_exist', models.BooleanField(verbose_name='Поддержка LTE')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
